# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required

# TODO Rust builds on stable by default, this can be
# overridden on a case by case basis down below.
matrix:
  allow_failures:
    - nightly
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Linux
    #- env: TARGET=aarch64-unknown-linux-gnu
    # Raspberry Pi
    - env: TARGET=arm-unknown-linux-gnueabi
    # Raspberry Pi 3...
    - env: TARGET=armv7-unknown-linux-gnueabihf

    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # Bare metal
    # These targets don't support std and as such are likely not suitable for
    # most crates.
    - env: TARGET=thumbv6m-none-eabi
    - env: TARGET=thumbv7em-none-eabi
    - env: TARGET=thumbv7em-none-eabihf
    - env: TARGET=thumbv7m-none-eabi


addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev


before_install:
  - set -e
  - rustup self update


install:
  - cargo install cargo-update || echo "cargo-update already installed"
  - cargo install-update -a # update outdated cached binaries
  - rustup target add thumbv7m-none-eabi
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview

  #TODO: remove -A clippy::new_ret_no_self when new version of clippy gets released!
script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings -A clippy::new_ret_no_self
  - cargo check  
  - cargo test --all-features --release
  - cargo doc --all-features --release
  - cd examples/epd4in2_full && cargo fmt --all -- --check && cargo check && cd ../../
  - cd examples/epd2in9_full && cargo fmt --all -- --check && cargo check && cd ../../
  - cd examples/epd1in54_full && cargo fmt --all -- --check && cargo check && cd ../../
  - cd examples/epd1in54_no_graphics && cargo fmt --all -- --check && cargo check && cd ../../
  - cd examples/epd4in2_var_display_buffer && cargo fmt --all -- --check && cargo check && cd ../../

after_success: 
# measure code coverage and upload to coveralls.io
  - cargo coveralls
#- cargo doc-upload



cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
