[package]
authors = ["Christoph Gro√ü <christoph-gross@mailbox.org>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "An embedded-hal based driver for ePaper displays from Waveshare"
documentation = "https://docs.rs/eink-waveshare-rs"
homepage = "https://github.com/Caemor/eink-waveshare-rs"
keywords = ["ePaper", "Display"]
license = "ISC"
name = "eink_waveshare_rs"
readme = "README.md"
repository = "https://github.com/Caemor/eink-waveshare-rs.git"
version = "0.1.2"

[badges]
# Travis CI: `repository` in format "<user>/<project>" is required.
# `branch` is optional; default is `master`
travis-ci = { repository = "Caemor/eink-waveshare-rs" }


[features]
default = ["epd1in54", "epd2in9", "epd4in2", "graphics"]

graphics = []
epd1in54 = []
epd2in9 = []
epd4in2 = []
# Activates the fast LUT for EPD4in2
epd4in2_fast_update = []

[dependencies]

embedded-graphics = "0.4.2"
#embedded-graphics = {git = "https://github.com/caemor/embedded-graphics", branch = "patch-1"}


[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.1"
