[package]
name = "embedded_linux_eink_example"
version = "0.1.0"
authors = ["Christoph Gro√ü <christoph-gross@mailbox.org>"]
edition = "2018"

[dependencies]

## The Only difference between this one and the one without default features sizewise seems to be a different .d-file Size (dependencies-file)
#epd_waveshare = { path = "../../"}
epd-waveshare = { path = "../../", default-features = false, features = ["epd4in2", "graphics"]}

embedded-graphics = "0.5.2"
embedded-hal = { version = "0.2.2", features = ["unproven"] }

stm32f1xx-hal = { version = "0.2", features = ["rt", "stm32f103" ] }
cortex-m = "0.5.0"
cortex-m-rt = { version = "0.6.6", features = ["device"] }
panic-semihosting = "0.5"
